### ISSUE TITLE
Unhandled promise rejection Message must be a string

### ISSUE THREAD

**Issue by SalemCode8** [arthurvasconcelos/vue-izitoast#6] opened 2018-05-27 07:41 UTC
When i run this code 

```javascript
this.$toast.show({
    position: 'topRight',
    color: 'green',
    icon: 'fas fa-check',
    message: 'Sidebar Added Successfully'
});
```

the toastr didn't appear and it gives me this error

`Unhandled promise rejection Message must be a string`

**Comment by karthiknk** [comment] 2019-04-15 07:13
@SalemCode8 is this issue resolved? i get that same error now

**Comment by dipu-bd** [comment] 2019-05-08 09:34
I am facing this error too

**Comment by arthurvasconcelos** [comment] 2019-08-29 20:29
Hi @SalemCode8, @karthiknk and @dipu-bd I was reviewing this issue and the problem is because you are calling `show` with wrong function signature.

The show method in vue-izitoast is called like this: `show(message, title = '', options = {})`.

Reference here: [v1.1.2](https://github.com/arthurvasconcelos/vue-izitoast/blob/806faf5e270e2d5bd0ab916c14af226e6acc7ce9/src/index.js#L69) and [v1.2.0](https://github.com/arthurvasconcelos/vue-izitoast/blob/98ef214d6b77f2666b878f23735cb07b6b27ed53/src/vue-izitoast.js#L116).

But this show me that I need to improve on the error message. This better error message will be released in the next version.

**Closed by arthurvasconcelos** 2019-08-29 20:29 UTC
Labels: bug
